// Adapated from https://github.com/google/cel-go/blob/fa20ec8537cd02b9a25f56d4e0f3693792dfe07d/test/proto3pb/test_all_types.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/pb/all_types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This proto tests that global enums are resolved correctly.
type GlobalEnum int32

const (
	GlobalEnum_GOO GlobalEnum = 0
	GlobalEnum_GAR GlobalEnum = 1
	GlobalEnum_GAZ GlobalEnum = 2
)

// Enum value maps for GlobalEnum.
var (
	GlobalEnum_name = map[int32]string{
		0: "GOO",
		1: "GAR",
		2: "GAZ",
	}
	GlobalEnum_value = map[string]int32{
		"GOO": 0,
		"GAR": 1,
		"GAZ": 2,
	}
)

func (x GlobalEnum) Enum() *GlobalEnum {
	p := new(GlobalEnum)
	*p = x
	return p
}

func (x GlobalEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GlobalEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_all_types_proto_enumTypes[0].Descriptor()
}

func (GlobalEnum) Type() protoreflect.EnumType {
	return &file_internal_pb_all_types_proto_enumTypes[0]
}

func (x GlobalEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GlobalEnum.Descriptor instead.
func (GlobalEnum) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_all_types_proto_rawDescGZIP(), []int{0}
}

type TestAllTypes_NestedEnum int32

const (
	TestAllTypes_FOO TestAllTypes_NestedEnum = 0
	TestAllTypes_BAR TestAllTypes_NestedEnum = 1
	TestAllTypes_BAZ TestAllTypes_NestedEnum = 2
)

// Enum value maps for TestAllTypes_NestedEnum.
var (
	TestAllTypes_NestedEnum_name = map[int32]string{
		0: "FOO",
		1: "BAR",
		2: "BAZ",
	}
	TestAllTypes_NestedEnum_value = map[string]int32{
		"FOO": 0,
		"BAR": 1,
		"BAZ": 2,
	}
)

func (x TestAllTypes_NestedEnum) Enum() *TestAllTypes_NestedEnum {
	p := new(TestAllTypes_NestedEnum)
	*p = x
	return p
}

func (x TestAllTypes_NestedEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestAllTypes_NestedEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_all_types_proto_enumTypes[1].Descriptor()
}

func (TestAllTypes_NestedEnum) Type() protoreflect.EnumType {
	return &file_internal_pb_all_types_proto_enumTypes[1]
}

func (x TestAllTypes_NestedEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestAllTypes_NestedEnum.Descriptor instead.
func (TestAllTypes_NestedEnum) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_all_types_proto_rawDescGZIP(), []int{0, 0}
}

type TestAllTypesOptional_NestedEnum int32

const (
	TestAllTypesOptional_FOO TestAllTypesOptional_NestedEnum = 0
	TestAllTypesOptional_BAR TestAllTypesOptional_NestedEnum = 1
	TestAllTypesOptional_BAZ TestAllTypesOptional_NestedEnum = 2
)

// Enum value maps for TestAllTypesOptional_NestedEnum.
var (
	TestAllTypesOptional_NestedEnum_name = map[int32]string{
		0: "FOO",
		1: "BAR",
		2: "BAZ",
	}
	TestAllTypesOptional_NestedEnum_value = map[string]int32{
		"FOO": 0,
		"BAR": 1,
		"BAZ": 2,
	}
)

func (x TestAllTypesOptional_NestedEnum) Enum() *TestAllTypesOptional_NestedEnum {
	p := new(TestAllTypesOptional_NestedEnum)
	*p = x
	return p
}

func (x TestAllTypesOptional_NestedEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestAllTypesOptional_NestedEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_all_types_proto_enumTypes[2].Descriptor()
}

func (TestAllTypesOptional_NestedEnum) Type() protoreflect.EnumType {
	return &file_internal_pb_all_types_proto_enumTypes[2]
}

func (x TestAllTypesOptional_NestedEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestAllTypesOptional_NestedEnum.Descriptor instead.
func (TestAllTypesOptional_NestedEnum) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_all_types_proto_rawDescGZIP(), []int{3, 0}
}

// This proto includes every type of field in both singular and repeated forms.
type TestAllTypes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Singular
	SingleInt32    int32                   `protobuf:"varint,1,opt,name=single_int32,json=singleInt32,proto3" json:"single_int32,omitempty"`
	SingleInt64    int64                   `protobuf:"varint,2,opt,name=single_int64,json=singleInt64,proto3" json:"single_int64,omitempty"`
	SingleUint32   uint32                  `protobuf:"varint,3,opt,name=single_uint32,json=singleUint32,proto3" json:"single_uint32,omitempty"`
	SingleUint64   uint64                  `protobuf:"varint,4,opt,name=single_uint64,json=singleUint64,proto3" json:"single_uint64,omitempty"`
	SingleSint32   int32                   `protobuf:"zigzag32,5,opt,name=single_sint32,json=singleSint32,proto3" json:"single_sint32,omitempty"`
	SingleSint64   int64                   `protobuf:"zigzag64,6,opt,name=single_sint64,json=singleSint64,proto3" json:"single_sint64,omitempty"`
	SingleFixed32  uint32                  `protobuf:"fixed32,7,opt,name=single_fixed32,json=singleFixed32,proto3" json:"single_fixed32,omitempty"`
	SingleFixed64  uint64                  `protobuf:"fixed64,8,opt,name=single_fixed64,json=singleFixed64,proto3" json:"single_fixed64,omitempty"`
	SingleSfixed32 int32                   `protobuf:"fixed32,9,opt,name=single_sfixed32,json=singleSfixed32,proto3" json:"single_sfixed32,omitempty"`
	SingleSfixed64 int64                   `protobuf:"fixed64,10,opt,name=single_sfixed64,json=singleSfixed64,proto3" json:"single_sfixed64,omitempty"`
	SingleFloat    float32                 `protobuf:"fixed32,11,opt,name=single_float,json=singleFloat,proto3" json:"single_float,omitempty"`
	SingleDouble   float64                 `protobuf:"fixed64,12,opt,name=single_double,json=singleDouble,proto3" json:"single_double,omitempty"`
	SingleBool     bool                    `protobuf:"varint,13,opt,name=single_bool,json=singleBool,proto3" json:"single_bool,omitempty"`
	SingleString   string                  `protobuf:"bytes,14,opt,name=single_string,json=singleString,proto3" json:"single_string,omitempty"`
	SingleBytes    []byte                  `protobuf:"bytes,15,opt,name=single_bytes,json=singleBytes,proto3" json:"single_bytes,omitempty"`
	StandaloneEnum TestAllTypes_NestedEnum `protobuf:"varint,22,opt,name=standalone_enum,json=standaloneEnum,proto3,enum=cerbos.hashpb.test.TestAllTypes_NestedEnum" json:"standalone_enum,omitempty"`
	// Wellknown.
	SingleAny           *anypb.Any              `protobuf:"bytes,100,opt,name=single_any,json=singleAny,proto3" json:"single_any,omitempty"`
	SingleDuration      *durationpb.Duration    `protobuf:"bytes,101,opt,name=single_duration,json=singleDuration,proto3" json:"single_duration,omitempty"`
	SingleTimestamp     *timestamppb.Timestamp  `protobuf:"bytes,102,opt,name=single_timestamp,json=singleTimestamp,proto3" json:"single_timestamp,omitempty"`
	SingleStruct        *structpb.Struct        `protobuf:"bytes,103,opt,name=single_struct,json=singleStruct,proto3" json:"single_struct,omitempty"`
	SingleValue         *structpb.Value         `protobuf:"bytes,104,opt,name=single_value,json=singleValue,proto3" json:"single_value,omitempty"`
	SingleInt64Wrapper  *wrapperspb.Int64Value  `protobuf:"bytes,105,opt,name=single_int64_wrapper,json=singleInt64Wrapper,proto3" json:"single_int64_wrapper,omitempty"`
	SingleInt32Wrapper  *wrapperspb.Int32Value  `protobuf:"bytes,106,opt,name=single_int32_wrapper,json=singleInt32Wrapper,proto3" json:"single_int32_wrapper,omitempty"`
	SingleDoubleWrapper *wrapperspb.DoubleValue `protobuf:"bytes,107,opt,name=single_double_wrapper,json=singleDoubleWrapper,proto3" json:"single_double_wrapper,omitempty"`
	SingleFloatWrapper  *wrapperspb.FloatValue  `protobuf:"bytes,108,opt,name=single_float_wrapper,json=singleFloatWrapper,proto3" json:"single_float_wrapper,omitempty"`
	SingleUint64Wrapper *wrapperspb.UInt64Value `protobuf:"bytes,109,opt,name=single_uint64_wrapper,json=singleUint64Wrapper,proto3" json:"single_uint64_wrapper,omitempty"`
	SingleUint32Wrapper *wrapperspb.UInt32Value `protobuf:"bytes,110,opt,name=single_uint32_wrapper,json=singleUint32Wrapper,proto3" json:"single_uint32_wrapper,omitempty"`
	SingleStringWrapper *wrapperspb.StringValue `protobuf:"bytes,111,opt,name=single_string_wrapper,json=singleStringWrapper,proto3" json:"single_string_wrapper,omitempty"`
	SingleBoolWrapper   *wrapperspb.BoolValue   `protobuf:"bytes,112,opt,name=single_bool_wrapper,json=singleBoolWrapper,proto3" json:"single_bool_wrapper,omitempty"`
	SingleBytesWrapper  *wrapperspb.BytesValue  `protobuf:"bytes,113,opt,name=single_bytes_wrapper,json=singleBytesWrapper,proto3" json:"single_bytes_wrapper,omitempty"`
	// Nested messages
	//
	// Types that are valid to be assigned to NestedType:
	//
	//	*TestAllTypes_SingleNestedMessage
	//	*TestAllTypes_SingleNestedEnum
	NestedType isTestAllTypes_NestedType `protobuf_oneof:"nested_type"`
	// Repeated
	RepeatedInt32         []int32                       `protobuf:"varint,31,rep,packed,name=repeated_int32,json=repeatedInt32,proto3" json:"repeated_int32,omitempty"`
	RepeatedInt64         []int64                       `protobuf:"varint,32,rep,packed,name=repeated_int64,json=repeatedInt64,proto3" json:"repeated_int64,omitempty"`
	RepeatedUint32        []uint32                      `protobuf:"varint,33,rep,packed,name=repeated_uint32,json=repeatedUint32,proto3" json:"repeated_uint32,omitempty"`
	RepeatedUint64        []uint64                      `protobuf:"varint,34,rep,packed,name=repeated_uint64,json=repeatedUint64,proto3" json:"repeated_uint64,omitempty"`
	RepeatedSint32        []int32                       `protobuf:"zigzag32,35,rep,packed,name=repeated_sint32,json=repeatedSint32,proto3" json:"repeated_sint32,omitempty"`
	RepeatedSint64        []int64                       `protobuf:"zigzag64,36,rep,packed,name=repeated_sint64,json=repeatedSint64,proto3" json:"repeated_sint64,omitempty"`
	RepeatedFixed32       []uint32                      `protobuf:"fixed32,37,rep,packed,name=repeated_fixed32,json=repeatedFixed32,proto3" json:"repeated_fixed32,omitempty"`
	RepeatedFixed64       []uint64                      `protobuf:"fixed64,38,rep,packed,name=repeated_fixed64,json=repeatedFixed64,proto3" json:"repeated_fixed64,omitempty"`
	RepeatedSfixed32      []int32                       `protobuf:"fixed32,39,rep,packed,name=repeated_sfixed32,json=repeatedSfixed32,proto3" json:"repeated_sfixed32,omitempty"`
	RepeatedSfixed64      []int64                       `protobuf:"fixed64,40,rep,packed,name=repeated_sfixed64,json=repeatedSfixed64,proto3" json:"repeated_sfixed64,omitempty"`
	RepeatedFloat         []float32                     `protobuf:"fixed32,41,rep,packed,name=repeated_float,json=repeatedFloat,proto3" json:"repeated_float,omitempty"`
	RepeatedDouble        []float64                     `protobuf:"fixed64,42,rep,packed,name=repeated_double,json=repeatedDouble,proto3" json:"repeated_double,omitempty"`
	RepeatedBool          []bool                        `protobuf:"varint,43,rep,packed,name=repeated_bool,json=repeatedBool,proto3" json:"repeated_bool,omitempty"`
	RepeatedString        []string                      `protobuf:"bytes,44,rep,name=repeated_string,json=repeatedString,proto3" json:"repeated_string,omitempty"`
	RepeatedBytes         [][]byte                      `protobuf:"bytes,45,rep,name=repeated_bytes,json=repeatedBytes,proto3" json:"repeated_bytes,omitempty"`
	RepeatedNestedMessage []*TestAllTypes_NestedMessage `protobuf:"bytes,48,rep,name=repeated_nested_message,json=repeatedNestedMessage,proto3" json:"repeated_nested_message,omitempty"`
	RepeatedNestedEnum    []TestAllTypes_NestedEnum     `protobuf:"varint,51,rep,packed,name=repeated_nested_enum,json=repeatedNestedEnum,proto3,enum=cerbos.hashpb.test.TestAllTypes_NestedEnum" json:"repeated_nested_enum,omitempty"`
	RepeatedStringPiece   []string                      `protobuf:"bytes,54,rep,name=repeated_string_piece,json=repeatedStringPiece,proto3" json:"repeated_string_piece,omitempty"`
	RepeatedCord          []string                      `protobuf:"bytes,55,rep,name=repeated_cord,json=repeatedCord,proto3" json:"repeated_cord,omitempty"`
	RepeatedLazyMessage   []*TestAllTypes_NestedMessage `protobuf:"bytes,57,rep,name=repeated_lazy_message,json=repeatedLazyMessage,proto3" json:"repeated_lazy_message,omitempty"`
	// Map
	MapStringString    map[string]string                     `protobuf:"bytes,58,rep,name=map_string_string,json=mapStringString,proto3" json:"map_string_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapUint64String    map[uint64]string                     `protobuf:"bytes,59,rep,name=map_uint64_string,json=mapUint64String,proto3" json:"map_uint64_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapInt32String     map[int32]string                      `protobuf:"bytes,60,rep,name=map_int32_string,json=mapInt32String,proto3" json:"map_int32_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapBoolString      map[bool]string                       `protobuf:"bytes,61,rep,name=map_bool_string,json=mapBoolString,proto3" json:"map_bool_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapInt64NestedType map[int64]*TestAllTypes_NestedMessage `protobuf:"bytes,62,rep,name=map_int64_nested_type,json=mapInt64NestedType,proto3" json:"map_int64_nested_type,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TestAllTypes) Reset() {
	*x = TestAllTypes{}
	mi := &file_internal_pb_all_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAllTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAllTypes) ProtoMessage() {}

func (x *TestAllTypes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_all_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAllTypes.ProtoReflect.Descriptor instead.
func (*TestAllTypes) Descriptor() ([]byte, []int) {
	return file_internal_pb_all_types_proto_rawDescGZIP(), []int{0}
}

func (x *TestAllTypes) GetSingleInt32() int32 {
	if x != nil {
		return x.SingleInt32
	}
	return 0
}

func (x *TestAllTypes) GetSingleInt64() int64 {
	if x != nil {
		return x.SingleInt64
	}
	return 0
}

func (x *TestAllTypes) GetSingleUint32() uint32 {
	if x != nil {
		return x.SingleUint32
	}
	return 0
}

func (x *TestAllTypes) GetSingleUint64() uint64 {
	if x != nil {
		return x.SingleUint64
	}
	return 0
}

func (x *TestAllTypes) GetSingleSint32() int32 {
	if x != nil {
		return x.SingleSint32
	}
	return 0
}

func (x *TestAllTypes) GetSingleSint64() int64 {
	if x != nil {
		return x.SingleSint64
	}
	return 0
}

func (x *TestAllTypes) GetSingleFixed32() uint32 {
	if x != nil {
		return x.SingleFixed32
	}
	return 0
}

func (x *TestAllTypes) GetSingleFixed64() uint64 {
	if x != nil {
		return x.SingleFixed64
	}
	return 0
}

func (x *TestAllTypes) GetSingleSfixed32() int32 {
	if x != nil {
		return x.SingleSfixed32
	}
	return 0
}

func (x *TestAllTypes) GetSingleSfixed64() int64 {
	if x != nil {
		return x.SingleSfixed64
	}
	return 0
}

func (x *TestAllTypes) GetSingleFloat() float32 {
	if x != nil {
		return x.SingleFloat
	}
	return 0
}

func (x *TestAllTypes) GetSingleDouble() float64 {
	if x != nil {
		return x.SingleDouble
	}
	return 0
}

func (x *TestAllTypes) GetSingleBool() bool {
	if x != nil {
		return x.SingleBool
	}
	return false
}

func (x *TestAllTypes) GetSingleString() string {
	if x != nil {
		return x.SingleString
	}
	return ""
}

func (x *TestAllTypes) GetSingleBytes() []byte {
	if x != nil {
		return x.SingleBytes
	}
	return nil
}

func (x *TestAllTypes) GetStandaloneEnum() TestAllTypes_NestedEnum {
	if x != nil {
		return x.StandaloneEnum
	}
	return TestAllTypes_FOO
}

func (x *TestAllTypes) GetSingleAny() *anypb.Any {
	if x != nil {
		return x.SingleAny
	}
	return nil
}

func (x *TestAllTypes) GetSingleDuration() *durationpb.Duration {
	if x != nil {
		return x.SingleDuration
	}
	return nil
}

func (x *TestAllTypes) GetSingleTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.SingleTimestamp
	}
	return nil
}

func (x *TestAllTypes) GetSingleStruct() *structpb.Struct {
	if x != nil {
		return x.SingleStruct
	}
	return nil
}

func (x *TestAllTypes) GetSingleValue() *structpb.Value {
	if x != nil {
		return x.SingleValue
	}
	return nil
}

func (x *TestAllTypes) GetSingleInt64Wrapper() *wrapperspb.Int64Value {
	if x != nil {
		return x.SingleInt64Wrapper
	}
	return nil
}

func (x *TestAllTypes) GetSingleInt32Wrapper() *wrapperspb.Int32Value {
	if x != nil {
		return x.SingleInt32Wrapper
	}
	return nil
}

func (x *TestAllTypes) GetSingleDoubleWrapper() *wrapperspb.DoubleValue {
	if x != nil {
		return x.SingleDoubleWrapper
	}
	return nil
}

func (x *TestAllTypes) GetSingleFloatWrapper() *wrapperspb.FloatValue {
	if x != nil {
		return x.SingleFloatWrapper
	}
	return nil
}

func (x *TestAllTypes) GetSingleUint64Wrapper() *wrapperspb.UInt64Value {
	if x != nil {
		return x.SingleUint64Wrapper
	}
	return nil
}

func (x *TestAllTypes) GetSingleUint32Wrapper() *wrapperspb.UInt32Value {
	if x != nil {
		return x.SingleUint32Wrapper
	}
	return nil
}

func (x *TestAllTypes) GetSingleStringWrapper() *wrapperspb.StringValue {
	if x != nil {
		return x.SingleStringWrapper
	}
	return nil
}

func (x *TestAllTypes) GetSingleBoolWrapper() *wrapperspb.BoolValue {
	if x != nil {
		return x.SingleBoolWrapper
	}
	return nil
}

func (x *TestAllTypes) GetSingleBytesWrapper() *wrapperspb.BytesValue {
	if x != nil {
		return x.SingleBytesWrapper
	}
	return nil
}

func (x *TestAllTypes) GetNestedType() isTestAllTypes_NestedType {
	if x != nil {
		return x.NestedType
	}
	return nil
}

func (x *TestAllTypes) GetSingleNestedMessage() *TestAllTypes_NestedMessage {
	if x != nil {
		if x, ok := x.NestedType.(*TestAllTypes_SingleNestedMessage); ok {
			return x.SingleNestedMessage
		}
	}
	return nil
}

func (x *TestAllTypes) GetSingleNestedEnum() TestAllTypes_NestedEnum {
	if x != nil {
		if x, ok := x.NestedType.(*TestAllTypes_SingleNestedEnum); ok {
			return x.SingleNestedEnum
		}
	}
	return TestAllTypes_FOO
}

func (x *TestAllTypes) GetRepeatedInt32() []int32 {
	if x != nil {
		return x.RepeatedInt32
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedInt64() []int64 {
	if x != nil {
		return x.RepeatedInt64
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedUint32() []uint32 {
	if x != nil {
		return x.RepeatedUint32
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedUint64() []uint64 {
	if x != nil {
		return x.RepeatedUint64
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedSint32() []int32 {
	if x != nil {
		return x.RepeatedSint32
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedSint64() []int64 {
	if x != nil {
		return x.RepeatedSint64
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedFixed32() []uint32 {
	if x != nil {
		return x.RepeatedFixed32
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedFixed64() []uint64 {
	if x != nil {
		return x.RepeatedFixed64
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedSfixed32() []int32 {
	if x != nil {
		return x.RepeatedSfixed32
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedSfixed64() []int64 {
	if x != nil {
		return x.RepeatedSfixed64
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedFloat() []float32 {
	if x != nil {
		return x.RepeatedFloat
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedDouble() []float64 {
	if x != nil {
		return x.RepeatedDouble
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedBool() []bool {
	if x != nil {
		return x.RepeatedBool
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedString() []string {
	if x != nil {
		return x.RepeatedString
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedBytes() [][]byte {
	if x != nil {
		return x.RepeatedBytes
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedNestedMessage() []*TestAllTypes_NestedMessage {
	if x != nil {
		return x.RepeatedNestedMessage
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedNestedEnum() []TestAllTypes_NestedEnum {
	if x != nil {
		return x.RepeatedNestedEnum
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedStringPiece() []string {
	if x != nil {
		return x.RepeatedStringPiece
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedCord() []string {
	if x != nil {
		return x.RepeatedCord
	}
	return nil
}

func (x *TestAllTypes) GetRepeatedLazyMessage() []*TestAllTypes_NestedMessage {
	if x != nil {
		return x.RepeatedLazyMessage
	}
	return nil
}

func (x *TestAllTypes) GetMapStringString() map[string]string {
	if x != nil {
		return x.MapStringString
	}
	return nil
}

func (x *TestAllTypes) GetMapUint64String() map[uint64]string {
	if x != nil {
		return x.MapUint64String
	}
	return nil
}

func (x *TestAllTypes) GetMapInt32String() map[int32]string {
	if x != nil {
		return x.MapInt32String
	}
	return nil
}

func (x *TestAllTypes) GetMapBoolString() map[bool]string {
	if x != nil {
		return x.MapBoolString
	}
	return nil
}

func (x *TestAllTypes) GetMapInt64NestedType() map[int64]*TestAllTypes_NestedMessage {
	if x != nil {
		return x.MapInt64NestedType
	}
	return nil
}

type isTestAllTypes_NestedType interface {
	isTestAllTypes_NestedType()
}

type TestAllTypes_SingleNestedMessage struct {
	SingleNestedMessage *TestAllTypes_NestedMessage `protobuf:"bytes,18,opt,name=single_nested_message,json=singleNestedMessage,proto3,oneof"`
}

type TestAllTypes_SingleNestedEnum struct {
	SingleNestedEnum TestAllTypes_NestedEnum `protobuf:"varint,21,opt,name=single_nested_enum,json=singleNestedEnum,proto3,enum=cerbos.hashpb.test.TestAllTypes_NestedEnum,oneof"`
}

func (*TestAllTypes_SingleNestedMessage) isTestAllTypes_NestedType() {}

func (*TestAllTypes_SingleNestedEnum) isTestAllTypes_NestedType() {}

// This proto includes a recursively nested message.
type NestedTestAllTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Child         *NestedTestAllTypes    `protobuf:"bytes,1,opt,name=child,proto3" json:"child,omitempty"`
	Payload       *TestAllTypes          `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedTestAllTypes) Reset() {
	*x = NestedTestAllTypes{}
	mi := &file_internal_pb_all_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedTestAllTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedTestAllTypes) ProtoMessage() {}

func (x *NestedTestAllTypes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_all_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedTestAllTypes.ProtoReflect.Descriptor instead.
func (*NestedTestAllTypes) Descriptor() ([]byte, []int) {
	return file_internal_pb_all_types_proto_rawDescGZIP(), []int{1}
}

func (x *NestedTestAllTypes) GetChild() *NestedTestAllTypes {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *NestedTestAllTypes) GetPayload() *TestAllTypes {
	if x != nil {
		return x.Payload
	}
	return nil
}

type NoFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoFields) Reset() {
	*x = NoFields{}
	mi := &file_internal_pb_all_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoFields) ProtoMessage() {}

func (x *NoFields) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_all_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoFields.ProtoReflect.Descriptor instead.
func (*NoFields) Descriptor() ([]byte, []int) {
	return file_internal_pb_all_types_proto_rawDescGZIP(), []int{2}
}

type TestAllTypesOptional struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Singular
	SingleInt32    *int32                           `protobuf:"varint,1,opt,name=single_int32,json=singleInt32,proto3,oneof" json:"single_int32,omitempty"`
	SingleInt64    *int64                           `protobuf:"varint,2,opt,name=single_int64,json=singleInt64,proto3,oneof" json:"single_int64,omitempty"`
	SingleUint32   *uint32                          `protobuf:"varint,3,opt,name=single_uint32,json=singleUint32,proto3,oneof" json:"single_uint32,omitempty"`
	SingleUint64   *uint64                          `protobuf:"varint,4,opt,name=single_uint64,json=singleUint64,proto3,oneof" json:"single_uint64,omitempty"`
	SingleSint32   *int32                           `protobuf:"zigzag32,5,opt,name=single_sint32,json=singleSint32,proto3,oneof" json:"single_sint32,omitempty"`
	SingleSint64   *int64                           `protobuf:"zigzag64,6,opt,name=single_sint64,json=singleSint64,proto3,oneof" json:"single_sint64,omitempty"`
	SingleFixed32  *uint32                          `protobuf:"fixed32,7,opt,name=single_fixed32,json=singleFixed32,proto3,oneof" json:"single_fixed32,omitempty"`
	SingleFixed64  *uint64                          `protobuf:"fixed64,8,opt,name=single_fixed64,json=singleFixed64,proto3,oneof" json:"single_fixed64,omitempty"`
	SingleSfixed32 *int32                           `protobuf:"fixed32,9,opt,name=single_sfixed32,json=singleSfixed32,proto3,oneof" json:"single_sfixed32,omitempty"`
	SingleSfixed64 *int64                           `protobuf:"fixed64,10,opt,name=single_sfixed64,json=singleSfixed64,proto3,oneof" json:"single_sfixed64,omitempty"`
	SingleFloat    *float32                         `protobuf:"fixed32,11,opt,name=single_float,json=singleFloat,proto3,oneof" json:"single_float,omitempty"`
	SingleDouble   *float64                         `protobuf:"fixed64,12,opt,name=single_double,json=singleDouble,proto3,oneof" json:"single_double,omitempty"`
	SingleBool     *bool                            `protobuf:"varint,13,opt,name=single_bool,json=singleBool,proto3,oneof" json:"single_bool,omitempty"`
	SingleString   *string                          `protobuf:"bytes,14,opt,name=single_string,json=singleString,proto3,oneof" json:"single_string,omitempty"`
	SingleBytes    []byte                           `protobuf:"bytes,15,opt,name=single_bytes,json=singleBytes,proto3,oneof" json:"single_bytes,omitempty"`
	StandaloneEnum *TestAllTypesOptional_NestedEnum `protobuf:"varint,22,opt,name=standalone_enum,json=standaloneEnum,proto3,enum=cerbos.hashpb.test.TestAllTypesOptional_NestedEnum,oneof" json:"standalone_enum,omitempty"`
	// Wellknown.
	SingleAny           *anypb.Any                          `protobuf:"bytes,100,opt,name=single_any,json=singleAny,proto3,oneof" json:"single_any,omitempty"`
	SingleDuration      *durationpb.Duration                `protobuf:"bytes,101,opt,name=single_duration,json=singleDuration,proto3,oneof" json:"single_duration,omitempty"`
	SingleTimestamp     *timestamppb.Timestamp              `protobuf:"bytes,102,opt,name=single_timestamp,json=singleTimestamp,proto3,oneof" json:"single_timestamp,omitempty"`
	SingleStruct        *structpb.Struct                    `protobuf:"bytes,103,opt,name=single_struct,json=singleStruct,proto3,oneof" json:"single_struct,omitempty"`
	SingleValue         *structpb.Value                     `protobuf:"bytes,104,opt,name=single_value,json=singleValue,proto3,oneof" json:"single_value,omitempty"`
	SingleInt64Wrapper  *wrapperspb.Int64Value              `protobuf:"bytes,105,opt,name=single_int64_wrapper,json=singleInt64Wrapper,proto3,oneof" json:"single_int64_wrapper,omitempty"`
	SingleInt32Wrapper  *wrapperspb.Int32Value              `protobuf:"bytes,106,opt,name=single_int32_wrapper,json=singleInt32Wrapper,proto3,oneof" json:"single_int32_wrapper,omitempty"`
	SingleDoubleWrapper *wrapperspb.DoubleValue             `protobuf:"bytes,107,opt,name=single_double_wrapper,json=singleDoubleWrapper,proto3,oneof" json:"single_double_wrapper,omitempty"`
	SingleFloatWrapper  *wrapperspb.FloatValue              `protobuf:"bytes,108,opt,name=single_float_wrapper,json=singleFloatWrapper,proto3,oneof" json:"single_float_wrapper,omitempty"`
	SingleUint64Wrapper *wrapperspb.UInt64Value             `protobuf:"bytes,109,opt,name=single_uint64_wrapper,json=singleUint64Wrapper,proto3,oneof" json:"single_uint64_wrapper,omitempty"`
	SingleUint32Wrapper *wrapperspb.UInt32Value             `protobuf:"bytes,110,opt,name=single_uint32_wrapper,json=singleUint32Wrapper,proto3,oneof" json:"single_uint32_wrapper,omitempty"`
	SingleStringWrapper *wrapperspb.StringValue             `protobuf:"bytes,111,opt,name=single_string_wrapper,json=singleStringWrapper,proto3,oneof" json:"single_string_wrapper,omitempty"`
	SingleBoolWrapper   *wrapperspb.BoolValue               `protobuf:"bytes,112,opt,name=single_bool_wrapper,json=singleBoolWrapper,proto3,oneof" json:"single_bool_wrapper,omitempty"`
	SingleBytesWrapper  *wrapperspb.BytesValue              `protobuf:"bytes,113,opt,name=single_bytes_wrapper,json=singleBytesWrapper,proto3,oneof" json:"single_bytes_wrapper,omitempty"`
	SingleNestedMessage *TestAllTypesOptional_NestedMessage `protobuf:"bytes,18,opt,name=single_nested_message,json=singleNestedMessage,proto3,oneof" json:"single_nested_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TestAllTypesOptional) Reset() {
	*x = TestAllTypesOptional{}
	mi := &file_internal_pb_all_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAllTypesOptional) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAllTypesOptional) ProtoMessage() {}

func (x *TestAllTypesOptional) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_all_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAllTypesOptional.ProtoReflect.Descriptor instead.
func (*TestAllTypesOptional) Descriptor() ([]byte, []int) {
	return file_internal_pb_all_types_proto_rawDescGZIP(), []int{3}
}

func (x *TestAllTypesOptional) GetSingleInt32() int32 {
	if x != nil && x.SingleInt32 != nil {
		return *x.SingleInt32
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleInt64() int64 {
	if x != nil && x.SingleInt64 != nil {
		return *x.SingleInt64
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleUint32() uint32 {
	if x != nil && x.SingleUint32 != nil {
		return *x.SingleUint32
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleUint64() uint64 {
	if x != nil && x.SingleUint64 != nil {
		return *x.SingleUint64
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleSint32() int32 {
	if x != nil && x.SingleSint32 != nil {
		return *x.SingleSint32
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleSint64() int64 {
	if x != nil && x.SingleSint64 != nil {
		return *x.SingleSint64
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleFixed32() uint32 {
	if x != nil && x.SingleFixed32 != nil {
		return *x.SingleFixed32
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleFixed64() uint64 {
	if x != nil && x.SingleFixed64 != nil {
		return *x.SingleFixed64
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleSfixed32() int32 {
	if x != nil && x.SingleSfixed32 != nil {
		return *x.SingleSfixed32
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleSfixed64() int64 {
	if x != nil && x.SingleSfixed64 != nil {
		return *x.SingleSfixed64
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleFloat() float32 {
	if x != nil && x.SingleFloat != nil {
		return *x.SingleFloat
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleDouble() float64 {
	if x != nil && x.SingleDouble != nil {
		return *x.SingleDouble
	}
	return 0
}

func (x *TestAllTypesOptional) GetSingleBool() bool {
	if x != nil && x.SingleBool != nil {
		return *x.SingleBool
	}
	return false
}

func (x *TestAllTypesOptional) GetSingleString() string {
	if x != nil && x.SingleString != nil {
		return *x.SingleString
	}
	return ""
}

func (x *TestAllTypesOptional) GetSingleBytes() []byte {
	if x != nil {
		return x.SingleBytes
	}
	return nil
}

func (x *TestAllTypesOptional) GetStandaloneEnum() TestAllTypesOptional_NestedEnum {
	if x != nil && x.StandaloneEnum != nil {
		return *x.StandaloneEnum
	}
	return TestAllTypesOptional_FOO
}

func (x *TestAllTypesOptional) GetSingleAny() *anypb.Any {
	if x != nil {
		return x.SingleAny
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleDuration() *durationpb.Duration {
	if x != nil {
		return x.SingleDuration
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.SingleTimestamp
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleStruct() *structpb.Struct {
	if x != nil {
		return x.SingleStruct
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleValue() *structpb.Value {
	if x != nil {
		return x.SingleValue
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleInt64Wrapper() *wrapperspb.Int64Value {
	if x != nil {
		return x.SingleInt64Wrapper
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleInt32Wrapper() *wrapperspb.Int32Value {
	if x != nil {
		return x.SingleInt32Wrapper
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleDoubleWrapper() *wrapperspb.DoubleValue {
	if x != nil {
		return x.SingleDoubleWrapper
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleFloatWrapper() *wrapperspb.FloatValue {
	if x != nil {
		return x.SingleFloatWrapper
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleUint64Wrapper() *wrapperspb.UInt64Value {
	if x != nil {
		return x.SingleUint64Wrapper
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleUint32Wrapper() *wrapperspb.UInt32Value {
	if x != nil {
		return x.SingleUint32Wrapper
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleStringWrapper() *wrapperspb.StringValue {
	if x != nil {
		return x.SingleStringWrapper
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleBoolWrapper() *wrapperspb.BoolValue {
	if x != nil {
		return x.SingleBoolWrapper
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleBytesWrapper() *wrapperspb.BytesValue {
	if x != nil {
		return x.SingleBytesWrapper
	}
	return nil
}

func (x *TestAllTypesOptional) GetSingleNestedMessage() *TestAllTypesOptional_NestedMessage {
	if x != nil {
		return x.SingleNestedMessage
	}
	return nil
}

type TestAllTypes_NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bb            int32                  `protobuf:"varint,1,opt,name=bb,proto3" json:"bb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAllTypes_NestedMessage) Reset() {
	*x = TestAllTypes_NestedMessage{}
	mi := &file_internal_pb_all_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAllTypes_NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAllTypes_NestedMessage) ProtoMessage() {}

func (x *TestAllTypes_NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_all_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAllTypes_NestedMessage.ProtoReflect.Descriptor instead.
func (*TestAllTypes_NestedMessage) Descriptor() ([]byte, []int) {
	return file_internal_pb_all_types_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TestAllTypes_NestedMessage) GetBb() int32 {
	if x != nil {
		return x.Bb
	}
	return 0
}

type NoFields_NestedMsg struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	NestedMessages map[string]*NestedTestAllTypes `protobuf:"bytes,1,rep,name=nested_messages,json=nestedMessages,proto3" json:"nested_messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NoFields_NestedMsg) Reset() {
	*x = NoFields_NestedMsg{}
	mi := &file_internal_pb_all_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoFields_NestedMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoFields_NestedMsg) ProtoMessage() {}

func (x *NoFields_NestedMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_all_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoFields_NestedMsg.ProtoReflect.Descriptor instead.
func (*NoFields_NestedMsg) Descriptor() ([]byte, []int) {
	return file_internal_pb_all_types_proto_rawDescGZIP(), []int{2, 0}
}

func (x *NoFields_NestedMsg) GetNestedMessages() map[string]*NestedTestAllTypes {
	if x != nil {
		return x.NestedMessages
	}
	return nil
}

type TestAllTypesOptional_NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bb            *int32                 `protobuf:"varint,1,opt,name=bb,proto3,oneof" json:"bb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAllTypesOptional_NestedMessage) Reset() {
	*x = TestAllTypesOptional_NestedMessage{}
	mi := &file_internal_pb_all_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAllTypesOptional_NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAllTypesOptional_NestedMessage) ProtoMessage() {}

func (x *TestAllTypesOptional_NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_all_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAllTypesOptional_NestedMessage.ProtoReflect.Descriptor instead.
func (*TestAllTypesOptional_NestedMessage) Descriptor() ([]byte, []int) {
	return file_internal_pb_all_types_proto_rawDescGZIP(), []int{3, 0}
}

func (x *TestAllTypesOptional_NestedMessage) GetBb() int32 {
	if x != nil && x.Bb != nil {
		return *x.Bb
	}
	return 0
}

var File_internal_pb_all_types_proto protoreflect.FileDescriptor

const file_internal_pb_all_types_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/pb/all_types.proto\x12\x12cerbos.hashpb.test\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9f\x1e\n" +
	"\fTestAllTypes\x12!\n" +
	"\fsingle_int32\x18\x01 \x01(\x05R\vsingleInt32\x12!\n" +
	"\fsingle_int64\x18\x02 \x01(\x03R\vsingleInt64\x12#\n" +
	"\rsingle_uint32\x18\x03 \x01(\rR\fsingleUint32\x12#\n" +
	"\rsingle_uint64\x18\x04 \x01(\x04R\fsingleUint64\x12#\n" +
	"\rsingle_sint32\x18\x05 \x01(\x11R\fsingleSint32\x12#\n" +
	"\rsingle_sint64\x18\x06 \x01(\x12R\fsingleSint64\x12%\n" +
	"\x0esingle_fixed32\x18\a \x01(\aR\rsingleFixed32\x12%\n" +
	"\x0esingle_fixed64\x18\b \x01(\x06R\rsingleFixed64\x12'\n" +
	"\x0fsingle_sfixed32\x18\t \x01(\x0fR\x0esingleSfixed32\x12'\n" +
	"\x0fsingle_sfixed64\x18\n" +
	" \x01(\x10R\x0esingleSfixed64\x12!\n" +
	"\fsingle_float\x18\v \x01(\x02R\vsingleFloat\x12#\n" +
	"\rsingle_double\x18\f \x01(\x01R\fsingleDouble\x12\x1f\n" +
	"\vsingle_bool\x18\r \x01(\bR\n" +
	"singleBool\x12#\n" +
	"\rsingle_string\x18\x0e \x01(\tR\fsingleString\x12!\n" +
	"\fsingle_bytes\x18\x0f \x01(\fR\vsingleBytes\x12T\n" +
	"\x0fstandalone_enum\x18\x16 \x01(\x0e2+.cerbos.hashpb.test.TestAllTypes.NestedEnumR\x0estandaloneEnum\x123\n" +
	"\n" +
	"single_any\x18d \x01(\v2\x14.google.protobuf.AnyR\tsingleAny\x12B\n" +
	"\x0fsingle_duration\x18e \x01(\v2\x19.google.protobuf.DurationR\x0esingleDuration\x12E\n" +
	"\x10single_timestamp\x18f \x01(\v2\x1a.google.protobuf.TimestampR\x0fsingleTimestamp\x12<\n" +
	"\rsingle_struct\x18g \x01(\v2\x17.google.protobuf.StructR\fsingleStruct\x129\n" +
	"\fsingle_value\x18h \x01(\v2\x16.google.protobuf.ValueR\vsingleValue\x12M\n" +
	"\x14single_int64_wrapper\x18i \x01(\v2\x1b.google.protobuf.Int64ValueR\x12singleInt64Wrapper\x12M\n" +
	"\x14single_int32_wrapper\x18j \x01(\v2\x1b.google.protobuf.Int32ValueR\x12singleInt32Wrapper\x12P\n" +
	"\x15single_double_wrapper\x18k \x01(\v2\x1c.google.protobuf.DoubleValueR\x13singleDoubleWrapper\x12M\n" +
	"\x14single_float_wrapper\x18l \x01(\v2\x1b.google.protobuf.FloatValueR\x12singleFloatWrapper\x12P\n" +
	"\x15single_uint64_wrapper\x18m \x01(\v2\x1c.google.protobuf.UInt64ValueR\x13singleUint64Wrapper\x12P\n" +
	"\x15single_uint32_wrapper\x18n \x01(\v2\x1c.google.protobuf.UInt32ValueR\x13singleUint32Wrapper\x12P\n" +
	"\x15single_string_wrapper\x18o \x01(\v2\x1c.google.protobuf.StringValueR\x13singleStringWrapper\x12J\n" +
	"\x13single_bool_wrapper\x18p \x01(\v2\x1a.google.protobuf.BoolValueR\x11singleBoolWrapper\x12M\n" +
	"\x14single_bytes_wrapper\x18q \x01(\v2\x1b.google.protobuf.BytesValueR\x12singleBytesWrapper\x12d\n" +
	"\x15single_nested_message\x18\x12 \x01(\v2..cerbos.hashpb.test.TestAllTypes.NestedMessageH\x00R\x13singleNestedMessage\x12[\n" +
	"\x12single_nested_enum\x18\x15 \x01(\x0e2+.cerbos.hashpb.test.TestAllTypes.NestedEnumH\x00R\x10singleNestedEnum\x12%\n" +
	"\x0erepeated_int32\x18\x1f \x03(\x05R\rrepeatedInt32\x12%\n" +
	"\x0erepeated_int64\x18  \x03(\x03R\rrepeatedInt64\x12'\n" +
	"\x0frepeated_uint32\x18! \x03(\rR\x0erepeatedUint32\x12'\n" +
	"\x0frepeated_uint64\x18\" \x03(\x04R\x0erepeatedUint64\x12'\n" +
	"\x0frepeated_sint32\x18# \x03(\x11R\x0erepeatedSint32\x12'\n" +
	"\x0frepeated_sint64\x18$ \x03(\x12R\x0erepeatedSint64\x12)\n" +
	"\x10repeated_fixed32\x18% \x03(\aR\x0frepeatedFixed32\x12)\n" +
	"\x10repeated_fixed64\x18& \x03(\x06R\x0frepeatedFixed64\x12+\n" +
	"\x11repeated_sfixed32\x18' \x03(\x0fR\x10repeatedSfixed32\x12+\n" +
	"\x11repeated_sfixed64\x18( \x03(\x10R\x10repeatedSfixed64\x12%\n" +
	"\x0erepeated_float\x18) \x03(\x02R\rrepeatedFloat\x12'\n" +
	"\x0frepeated_double\x18* \x03(\x01R\x0erepeatedDouble\x12#\n" +
	"\rrepeated_bool\x18+ \x03(\bR\frepeatedBool\x12'\n" +
	"\x0frepeated_string\x18, \x03(\tR\x0erepeatedString\x12%\n" +
	"\x0erepeated_bytes\x18- \x03(\fR\rrepeatedBytes\x12f\n" +
	"\x17repeated_nested_message\x180 \x03(\v2..cerbos.hashpb.test.TestAllTypes.NestedMessageR\x15repeatedNestedMessage\x12]\n" +
	"\x14repeated_nested_enum\x183 \x03(\x0e2+.cerbos.hashpb.test.TestAllTypes.NestedEnumR\x12repeatedNestedEnum\x126\n" +
	"\x15repeated_string_piece\x186 \x03(\tB\x02\b\x02R\x13repeatedStringPiece\x12'\n" +
	"\rrepeated_cord\x187 \x03(\tB\x02\b\x01R\frepeatedCord\x12f\n" +
	"\x15repeated_lazy_message\x189 \x03(\v2..cerbos.hashpb.test.TestAllTypes.NestedMessageB\x02(\x01R\x13repeatedLazyMessage\x12a\n" +
	"\x11map_string_string\x18: \x03(\v25.cerbos.hashpb.test.TestAllTypes.MapStringStringEntryR\x0fmapStringString\x12a\n" +
	"\x11map_uint64_string\x18; \x03(\v25.cerbos.hashpb.test.TestAllTypes.MapUint64StringEntryR\x0fmapUint64String\x12^\n" +
	"\x10map_int32_string\x18< \x03(\v24.cerbos.hashpb.test.TestAllTypes.MapInt32StringEntryR\x0emapInt32String\x12[\n" +
	"\x0fmap_bool_string\x18= \x03(\v23.cerbos.hashpb.test.TestAllTypes.MapBoolStringEntryR\rmapBoolString\x12k\n" +
	"\x15map_int64_nested_type\x18> \x03(\v28.cerbos.hashpb.test.TestAllTypes.MapInt64NestedTypeEntryR\x12mapInt64NestedType\x1a\x1f\n" +
	"\rNestedMessage\x12\x0e\n" +
	"\x02bb\x18\x01 \x01(\x05R\x02bb\x1aB\n" +
	"\x14MapStringStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14MapUint64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13MapInt32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12MapBoolStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1au\n" +
	"\x17MapInt64NestedTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12D\n" +
	"\x05value\x18\x02 \x01(\v2..cerbos.hashpb.test.TestAllTypes.NestedMessageR\x05value:\x028\x01\"'\n" +
	"\n" +
	"NestedEnum\x12\a\n" +
	"\x03FOO\x10\x00\x12\a\n" +
	"\x03BAR\x10\x01\x12\a\n" +
	"\x03BAZ\x10\x02B\r\n" +
	"\vnested_type\"\x8e\x01\n" +
	"\x12NestedTestAllTypes\x12<\n" +
	"\x05child\x18\x01 \x01(\v2&.cerbos.hashpb.test.NestedTestAllTypesR\x05child\x12:\n" +
	"\apayload\x18\x02 \x01(\v2 .cerbos.hashpb.test.TestAllTypesR\apayload\"\xe8\x01\n" +
	"\bNoFields\x1a\xdb\x01\n" +
	"\tNestedMsg\x12c\n" +
	"\x0fnested_messages\x18\x01 \x03(\v2:.cerbos.hashpb.test.NoFields.NestedMsg.NestedMessagesEntryR\x0enestedMessages\x1ai\n" +
	"\x13NestedMessagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.cerbos.hashpb.test.NestedTestAllTypesR\x05value:\x028\x01\"\x80\x15\n" +
	"\x14TestAllTypesOptional\x12&\n" +
	"\fsingle_int32\x18\x01 \x01(\x05H\x00R\vsingleInt32\x88\x01\x01\x12&\n" +
	"\fsingle_int64\x18\x02 \x01(\x03H\x01R\vsingleInt64\x88\x01\x01\x12(\n" +
	"\rsingle_uint32\x18\x03 \x01(\rH\x02R\fsingleUint32\x88\x01\x01\x12(\n" +
	"\rsingle_uint64\x18\x04 \x01(\x04H\x03R\fsingleUint64\x88\x01\x01\x12(\n" +
	"\rsingle_sint32\x18\x05 \x01(\x11H\x04R\fsingleSint32\x88\x01\x01\x12(\n" +
	"\rsingle_sint64\x18\x06 \x01(\x12H\x05R\fsingleSint64\x88\x01\x01\x12*\n" +
	"\x0esingle_fixed32\x18\a \x01(\aH\x06R\rsingleFixed32\x88\x01\x01\x12*\n" +
	"\x0esingle_fixed64\x18\b \x01(\x06H\aR\rsingleFixed64\x88\x01\x01\x12,\n" +
	"\x0fsingle_sfixed32\x18\t \x01(\x0fH\bR\x0esingleSfixed32\x88\x01\x01\x12,\n" +
	"\x0fsingle_sfixed64\x18\n" +
	" \x01(\x10H\tR\x0esingleSfixed64\x88\x01\x01\x12&\n" +
	"\fsingle_float\x18\v \x01(\x02H\n" +
	"R\vsingleFloat\x88\x01\x01\x12(\n" +
	"\rsingle_double\x18\f \x01(\x01H\vR\fsingleDouble\x88\x01\x01\x12$\n" +
	"\vsingle_bool\x18\r \x01(\bH\fR\n" +
	"singleBool\x88\x01\x01\x12(\n" +
	"\rsingle_string\x18\x0e \x01(\tH\rR\fsingleString\x88\x01\x01\x12&\n" +
	"\fsingle_bytes\x18\x0f \x01(\fH\x0eR\vsingleBytes\x88\x01\x01\x12a\n" +
	"\x0fstandalone_enum\x18\x16 \x01(\x0e23.cerbos.hashpb.test.TestAllTypesOptional.NestedEnumH\x0fR\x0estandaloneEnum\x88\x01\x01\x128\n" +
	"\n" +
	"single_any\x18d \x01(\v2\x14.google.protobuf.AnyH\x10R\tsingleAny\x88\x01\x01\x12G\n" +
	"\x0fsingle_duration\x18e \x01(\v2\x19.google.protobuf.DurationH\x11R\x0esingleDuration\x88\x01\x01\x12J\n" +
	"\x10single_timestamp\x18f \x01(\v2\x1a.google.protobuf.TimestampH\x12R\x0fsingleTimestamp\x88\x01\x01\x12A\n" +
	"\rsingle_struct\x18g \x01(\v2\x17.google.protobuf.StructH\x13R\fsingleStruct\x88\x01\x01\x12>\n" +
	"\fsingle_value\x18h \x01(\v2\x16.google.protobuf.ValueH\x14R\vsingleValue\x88\x01\x01\x12R\n" +
	"\x14single_int64_wrapper\x18i \x01(\v2\x1b.google.protobuf.Int64ValueH\x15R\x12singleInt64Wrapper\x88\x01\x01\x12R\n" +
	"\x14single_int32_wrapper\x18j \x01(\v2\x1b.google.protobuf.Int32ValueH\x16R\x12singleInt32Wrapper\x88\x01\x01\x12U\n" +
	"\x15single_double_wrapper\x18k \x01(\v2\x1c.google.protobuf.DoubleValueH\x17R\x13singleDoubleWrapper\x88\x01\x01\x12R\n" +
	"\x14single_float_wrapper\x18l \x01(\v2\x1b.google.protobuf.FloatValueH\x18R\x12singleFloatWrapper\x88\x01\x01\x12U\n" +
	"\x15single_uint64_wrapper\x18m \x01(\v2\x1c.google.protobuf.UInt64ValueH\x19R\x13singleUint64Wrapper\x88\x01\x01\x12U\n" +
	"\x15single_uint32_wrapper\x18n \x01(\v2\x1c.google.protobuf.UInt32ValueH\x1aR\x13singleUint32Wrapper\x88\x01\x01\x12U\n" +
	"\x15single_string_wrapper\x18o \x01(\v2\x1c.google.protobuf.StringValueH\x1bR\x13singleStringWrapper\x88\x01\x01\x12O\n" +
	"\x13single_bool_wrapper\x18p \x01(\v2\x1a.google.protobuf.BoolValueH\x1cR\x11singleBoolWrapper\x88\x01\x01\x12R\n" +
	"\x14single_bytes_wrapper\x18q \x01(\v2\x1b.google.protobuf.BytesValueH\x1dR\x12singleBytesWrapper\x88\x01\x01\x12o\n" +
	"\x15single_nested_message\x18\x12 \x01(\v26.cerbos.hashpb.test.TestAllTypesOptional.NestedMessageH\x1eR\x13singleNestedMessage\x88\x01\x01\x1a+\n" +
	"\rNestedMessage\x12\x13\n" +
	"\x02bb\x18\x01 \x01(\x05H\x00R\x02bb\x88\x01\x01B\x05\n" +
	"\x03_bb\"'\n" +
	"\n" +
	"NestedEnum\x12\a\n" +
	"\x03FOO\x10\x00\x12\a\n" +
	"\x03BAR\x10\x01\x12\a\n" +
	"\x03BAZ\x10\x02B\x0f\n" +
	"\r_single_int32B\x0f\n" +
	"\r_single_int64B\x10\n" +
	"\x0e_single_uint32B\x10\n" +
	"\x0e_single_uint64B\x10\n" +
	"\x0e_single_sint32B\x10\n" +
	"\x0e_single_sint64B\x11\n" +
	"\x0f_single_fixed32B\x11\n" +
	"\x0f_single_fixed64B\x12\n" +
	"\x10_single_sfixed32B\x12\n" +
	"\x10_single_sfixed64B\x0f\n" +
	"\r_single_floatB\x10\n" +
	"\x0e_single_doubleB\x0e\n" +
	"\f_single_boolB\x10\n" +
	"\x0e_single_stringB\x0f\n" +
	"\r_single_bytesB\x12\n" +
	"\x10_standalone_enumB\r\n" +
	"\v_single_anyB\x12\n" +
	"\x10_single_durationB\x13\n" +
	"\x11_single_timestampB\x10\n" +
	"\x0e_single_structB\x0f\n" +
	"\r_single_valueB\x17\n" +
	"\x15_single_int64_wrapperB\x17\n" +
	"\x15_single_int32_wrapperB\x18\n" +
	"\x16_single_double_wrapperB\x17\n" +
	"\x15_single_float_wrapperB\x18\n" +
	"\x16_single_uint64_wrapperB\x18\n" +
	"\x16_single_uint32_wrapperB\x18\n" +
	"\x16_single_string_wrapperB\x16\n" +
	"\x14_single_bool_wrapperB\x17\n" +
	"\x15_single_bytes_wrapperB\x18\n" +
	"\x16_single_nested_message*'\n" +
	"\n" +
	"GlobalEnum\x12\a\n" +
	"\x03GOO\x10\x00\x12\a\n" +
	"\x03GAR\x10\x01\x12\a\n" +
	"\x03GAZ\x10\x02B4Z2github.com/cerbos/protoc-gen-go-hashpb/internal/pbb\x06proto3"

var (
	file_internal_pb_all_types_proto_rawDescOnce sync.Once
	file_internal_pb_all_types_proto_rawDescData []byte
)

func file_internal_pb_all_types_proto_rawDescGZIP() []byte {
	file_internal_pb_all_types_proto_rawDescOnce.Do(func() {
		file_internal_pb_all_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_all_types_proto_rawDesc), len(file_internal_pb_all_types_proto_rawDesc)))
	})
	return file_internal_pb_all_types_proto_rawDescData
}

var file_internal_pb_all_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_pb_all_types_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_pb_all_types_proto_goTypes = []any{
	(GlobalEnum)(0),                      // 0: cerbos.hashpb.test.GlobalEnum
	(TestAllTypes_NestedEnum)(0),         // 1: cerbos.hashpb.test.TestAllTypes.NestedEnum
	(TestAllTypesOptional_NestedEnum)(0), // 2: cerbos.hashpb.test.TestAllTypesOptional.NestedEnum
	(*TestAllTypes)(nil),                 // 3: cerbos.hashpb.test.TestAllTypes
	(*NestedTestAllTypes)(nil),           // 4: cerbos.hashpb.test.NestedTestAllTypes
	(*NoFields)(nil),                     // 5: cerbos.hashpb.test.NoFields
	(*TestAllTypesOptional)(nil),         // 6: cerbos.hashpb.test.TestAllTypesOptional
	(*TestAllTypes_NestedMessage)(nil),   // 7: cerbos.hashpb.test.TestAllTypes.NestedMessage
	nil,                                  // 8: cerbos.hashpb.test.TestAllTypes.MapStringStringEntry
	nil,                                  // 9: cerbos.hashpb.test.TestAllTypes.MapUint64StringEntry
	nil,                                  // 10: cerbos.hashpb.test.TestAllTypes.MapInt32StringEntry
	nil,                                  // 11: cerbos.hashpb.test.TestAllTypes.MapBoolStringEntry
	nil,                                  // 12: cerbos.hashpb.test.TestAllTypes.MapInt64NestedTypeEntry
	(*NoFields_NestedMsg)(nil),           // 13: cerbos.hashpb.test.NoFields.NestedMsg
	nil,                                  // 14: cerbos.hashpb.test.NoFields.NestedMsg.NestedMessagesEntry
	(*TestAllTypesOptional_NestedMessage)(nil), // 15: cerbos.hashpb.test.TestAllTypesOptional.NestedMessage
	(*anypb.Any)(nil),                          // 16: google.protobuf.Any
	(*durationpb.Duration)(nil),                // 17: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),              // 18: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                    // 19: google.protobuf.Struct
	(*structpb.Value)(nil),                     // 20: google.protobuf.Value
	(*wrapperspb.Int64Value)(nil),              // 21: google.protobuf.Int64Value
	(*wrapperspb.Int32Value)(nil),              // 22: google.protobuf.Int32Value
	(*wrapperspb.DoubleValue)(nil),             // 23: google.protobuf.DoubleValue
	(*wrapperspb.FloatValue)(nil),              // 24: google.protobuf.FloatValue
	(*wrapperspb.UInt64Value)(nil),             // 25: google.protobuf.UInt64Value
	(*wrapperspb.UInt32Value)(nil),             // 26: google.protobuf.UInt32Value
	(*wrapperspb.StringValue)(nil),             // 27: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),               // 28: google.protobuf.BoolValue
	(*wrapperspb.BytesValue)(nil),              // 29: google.protobuf.BytesValue
}
var file_internal_pb_all_types_proto_depIdxs = []int32{
	1,  // 0: cerbos.hashpb.test.TestAllTypes.standalone_enum:type_name -> cerbos.hashpb.test.TestAllTypes.NestedEnum
	16, // 1: cerbos.hashpb.test.TestAllTypes.single_any:type_name -> google.protobuf.Any
	17, // 2: cerbos.hashpb.test.TestAllTypes.single_duration:type_name -> google.protobuf.Duration
	18, // 3: cerbos.hashpb.test.TestAllTypes.single_timestamp:type_name -> google.protobuf.Timestamp
	19, // 4: cerbos.hashpb.test.TestAllTypes.single_struct:type_name -> google.protobuf.Struct
	20, // 5: cerbos.hashpb.test.TestAllTypes.single_value:type_name -> google.protobuf.Value
	21, // 6: cerbos.hashpb.test.TestAllTypes.single_int64_wrapper:type_name -> google.protobuf.Int64Value
	22, // 7: cerbos.hashpb.test.TestAllTypes.single_int32_wrapper:type_name -> google.protobuf.Int32Value
	23, // 8: cerbos.hashpb.test.TestAllTypes.single_double_wrapper:type_name -> google.protobuf.DoubleValue
	24, // 9: cerbos.hashpb.test.TestAllTypes.single_float_wrapper:type_name -> google.protobuf.FloatValue
	25, // 10: cerbos.hashpb.test.TestAllTypes.single_uint64_wrapper:type_name -> google.protobuf.UInt64Value
	26, // 11: cerbos.hashpb.test.TestAllTypes.single_uint32_wrapper:type_name -> google.protobuf.UInt32Value
	27, // 12: cerbos.hashpb.test.TestAllTypes.single_string_wrapper:type_name -> google.protobuf.StringValue
	28, // 13: cerbos.hashpb.test.TestAllTypes.single_bool_wrapper:type_name -> google.protobuf.BoolValue
	29, // 14: cerbos.hashpb.test.TestAllTypes.single_bytes_wrapper:type_name -> google.protobuf.BytesValue
	7,  // 15: cerbos.hashpb.test.TestAllTypes.single_nested_message:type_name -> cerbos.hashpb.test.TestAllTypes.NestedMessage
	1,  // 16: cerbos.hashpb.test.TestAllTypes.single_nested_enum:type_name -> cerbos.hashpb.test.TestAllTypes.NestedEnum
	7,  // 17: cerbos.hashpb.test.TestAllTypes.repeated_nested_message:type_name -> cerbos.hashpb.test.TestAllTypes.NestedMessage
	1,  // 18: cerbos.hashpb.test.TestAllTypes.repeated_nested_enum:type_name -> cerbos.hashpb.test.TestAllTypes.NestedEnum
	7,  // 19: cerbos.hashpb.test.TestAllTypes.repeated_lazy_message:type_name -> cerbos.hashpb.test.TestAllTypes.NestedMessage
	8,  // 20: cerbos.hashpb.test.TestAllTypes.map_string_string:type_name -> cerbos.hashpb.test.TestAllTypes.MapStringStringEntry
	9,  // 21: cerbos.hashpb.test.TestAllTypes.map_uint64_string:type_name -> cerbos.hashpb.test.TestAllTypes.MapUint64StringEntry
	10, // 22: cerbos.hashpb.test.TestAllTypes.map_int32_string:type_name -> cerbos.hashpb.test.TestAllTypes.MapInt32StringEntry
	11, // 23: cerbos.hashpb.test.TestAllTypes.map_bool_string:type_name -> cerbos.hashpb.test.TestAllTypes.MapBoolStringEntry
	12, // 24: cerbos.hashpb.test.TestAllTypes.map_int64_nested_type:type_name -> cerbos.hashpb.test.TestAllTypes.MapInt64NestedTypeEntry
	4,  // 25: cerbos.hashpb.test.NestedTestAllTypes.child:type_name -> cerbos.hashpb.test.NestedTestAllTypes
	3,  // 26: cerbos.hashpb.test.NestedTestAllTypes.payload:type_name -> cerbos.hashpb.test.TestAllTypes
	2,  // 27: cerbos.hashpb.test.TestAllTypesOptional.standalone_enum:type_name -> cerbos.hashpb.test.TestAllTypesOptional.NestedEnum
	16, // 28: cerbos.hashpb.test.TestAllTypesOptional.single_any:type_name -> google.protobuf.Any
	17, // 29: cerbos.hashpb.test.TestAllTypesOptional.single_duration:type_name -> google.protobuf.Duration
	18, // 30: cerbos.hashpb.test.TestAllTypesOptional.single_timestamp:type_name -> google.protobuf.Timestamp
	19, // 31: cerbos.hashpb.test.TestAllTypesOptional.single_struct:type_name -> google.protobuf.Struct
	20, // 32: cerbos.hashpb.test.TestAllTypesOptional.single_value:type_name -> google.protobuf.Value
	21, // 33: cerbos.hashpb.test.TestAllTypesOptional.single_int64_wrapper:type_name -> google.protobuf.Int64Value
	22, // 34: cerbos.hashpb.test.TestAllTypesOptional.single_int32_wrapper:type_name -> google.protobuf.Int32Value
	23, // 35: cerbos.hashpb.test.TestAllTypesOptional.single_double_wrapper:type_name -> google.protobuf.DoubleValue
	24, // 36: cerbos.hashpb.test.TestAllTypesOptional.single_float_wrapper:type_name -> google.protobuf.FloatValue
	25, // 37: cerbos.hashpb.test.TestAllTypesOptional.single_uint64_wrapper:type_name -> google.protobuf.UInt64Value
	26, // 38: cerbos.hashpb.test.TestAllTypesOptional.single_uint32_wrapper:type_name -> google.protobuf.UInt32Value
	27, // 39: cerbos.hashpb.test.TestAllTypesOptional.single_string_wrapper:type_name -> google.protobuf.StringValue
	28, // 40: cerbos.hashpb.test.TestAllTypesOptional.single_bool_wrapper:type_name -> google.protobuf.BoolValue
	29, // 41: cerbos.hashpb.test.TestAllTypesOptional.single_bytes_wrapper:type_name -> google.protobuf.BytesValue
	15, // 42: cerbos.hashpb.test.TestAllTypesOptional.single_nested_message:type_name -> cerbos.hashpb.test.TestAllTypesOptional.NestedMessage
	7,  // 43: cerbos.hashpb.test.TestAllTypes.MapInt64NestedTypeEntry.value:type_name -> cerbos.hashpb.test.TestAllTypes.NestedMessage
	14, // 44: cerbos.hashpb.test.NoFields.NestedMsg.nested_messages:type_name -> cerbos.hashpb.test.NoFields.NestedMsg.NestedMessagesEntry
	4,  // 45: cerbos.hashpb.test.NoFields.NestedMsg.NestedMessagesEntry.value:type_name -> cerbos.hashpb.test.NestedTestAllTypes
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_internal_pb_all_types_proto_init() }
func file_internal_pb_all_types_proto_init() {
	if File_internal_pb_all_types_proto != nil {
		return
	}
	file_internal_pb_all_types_proto_msgTypes[0].OneofWrappers = []any{
		(*TestAllTypes_SingleNestedMessage)(nil),
		(*TestAllTypes_SingleNestedEnum)(nil),
	}
	file_internal_pb_all_types_proto_msgTypes[3].OneofWrappers = []any{}
	file_internal_pb_all_types_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_all_types_proto_rawDesc), len(file_internal_pb_all_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_all_types_proto_goTypes,
		DependencyIndexes: file_internal_pb_all_types_proto_depIdxs,
		EnumInfos:         file_internal_pb_all_types_proto_enumTypes,
		MessageInfos:      file_internal_pb_all_types_proto_msgTypes,
	}.Build()
	File_internal_pb_all_types_proto = out.File
	file_internal_pb_all_types_proto_goTypes = nil
	file_internal_pb_all_types_proto_depIdxs = nil
}
